# Gradle
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -XX:-MaxFDLimit
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# Kotlin
kotlinVersion=1.9.10

kotlin.code.style=official
#kotlin.js.compiler=ir

# dukat
kotlin.js.experimental.generateKotlinExternals = false

dokkaVersion=1.9.0
versionsVersion=0.47.0

ktsTargetAndroid=false
ktsTargetiOS=false

